### ISSUE TITLE
With the miniapp already open, open it again with a different button, hoping to carry parameters

### ISSUE THREAD

**Issue by zhengdechang** [Telegram-Mini-Apps/issues#44] opened 2024-09-11 15:05 UTC
**Is your feature request related to a problem? Please describe.**
The telegram bot has two buttons when it returns, one with parameters and one without parameters, I open the one with parameters after I have opened miniaop without parameters, always open the first one, only when I close the first one can open the one with parameters. How do we solve this

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by heyqbnk** [comment] 2024-11-20 16:57
Please provide more precise explanations on what the problem is. Closing until then

**Closed as not planned by heyqbnk** 2024-11-20 16:57 UTC
Labels: enhancement
